config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resource :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in:
   %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true },
    inclusion: { in: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    # @reviews = Review.find_by(restaurant_id: @restaurant.id)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(allowed_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(allowed_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  private

  def allowed_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(allowed_params)
    # @review.restaurant = Restaurant.find(params[:review][:restaurants_id])
    @review.save
    redirect_to restaurant_path(@review.restaurant_id)
  end

  private

  def allowed_params
    params.require(:review).permit(:content, :rating, :restaurant_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container">
    <h1>Create a new restaurant</h1>
    <%= simple_form_for @restaurant do |f| %>
    <%= f.input :name %>
    <%= f.input :address  %>
    <%= f.input :category  %>
    <%= f.input :phone_number  %>
    <%= f.submit "Add Restaurant", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/edit.html.erb
<%= render 'form', restaurant: @restaurant %>
<div class="container">
  <%= link_to "Go back to restaurant", restaurant_path(@restaurant) %>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>My restaurants</h1>
  <% @restaurants.each do |restaurant|%>
  <%= link_to restaurant.name, restaurant_path(restaurant) %> <br>
  <% end %>

  <%= link_to "Add a restaurant", new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>
<div class="container">
  <%= link_to "Go back to list of restaurants", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<div class="text">
  <h1><%= @restaurant.name %></h1>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.category %></p>
  <p><%= @restaurant.phone_number %></p>
  <%= link_to "Your restaurants", restaurants_path %> <br>
  <hr>
  <ul>
    <% @restaurant.reviews.each do |review| %>
    <li><%= review.rating %></li>
    <li><%= review.content %></li>
    <% end %>
  </ul>
<%= link_to "Edit restaurant", edit_restaurant_path(@restaurant) %> <br>
<%= link_to "Create reviews",  new_restaurant_reviews_path(@restaurant) %>
</div>

app/views/reviews/new.html.erb
<div class="container text">
    <h1>Create a new review</h1>
    <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.hidden_field :restaurant_id, value: @restaurant.id %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "Add Review", class: "btn btn-primary" %> <br>
    <%= link_to "Go back", restaurant_path(@restaurant) %>
  <% end %>
</div>